export type ThemeColors = {
    primary: string;
    planMode: string;
    selection: string;
    thinking: string;
    success: string;
    error: string;
    info: string;
    background: string;
    surface: string;
    dialogSurface: string;
    thinkingBoarder: string;
    dimSeparator: string;
};

export type Theme = {
    name: string;
    colors: ThemeColors;
};

export const THEMES: Theme[] = [
    {
        name: "Nightfox",
        colors: {
            primary: "#56D6C2",
            planMode: "#CF8EF4",
            selection: "#89B4FA",
            thinking: "#CF8EF4",
            success: "#82E0AA",
            error: "#E74C5E",
            info: "#56D6C2",
            background: "#0D0D12",
            surface: "#1A1A24",
            dialogSurface: "#0A0A10",
            thinkingBoarder: "#34344A",
            dimSeparator: "#4E4E66",
        },
    },
    {
        name: "Aurora Borealis",
        colors: {
            primary: "#79E8C5",
            planMode: "#B48EF7",
            selection: "#7EC8E3",
            thinking: "#B48EF7",
            success: "#6FD9A0",
            error: "#F47B7B",
            info: "#79E8C5",
            background: "#0B1120",
            surface: "#121D30",
            dialogSurface: "#080E1A",
            thinkingBoarder: "#1E3048",
            dimSeparator: "#2A4460",
        },
    },
    {
        name: "Tokyo Night",
        colors: {
            primary: "#7DCFFF",
            planMode: "#BB9AF7",
            selection: "#3D59A1",
            thinking: "#BB9AF7",
            success: "#9ECE6A",
            error: "#F7768E",
            info: "#7DCFFF",
            background: "#1A1B2E",
            surface: "#24283B",
            dialogSurface: "#13141F",
            thinkingBoarder: "#2F334D",
            dimSeparator: "#414868",
        },
    },
    {
        name: "Rosé Pine",
        colors: {
            primary: "#EBBCBA",
            planMode: "#C4A7E7",
            selection: "#9CCFD8",
            thinking: "#C4A7E7",
            success: "#31748F",
            error: "#EB6F92",
            info: "#EBBCBA",
            background: "#191724",
            surface: "#1F1D2E",
            dialogSurface: "#120F1D",
            thinkingBoarder: "#26233A",
            dimSeparator: "#6E6A86",
        },
    },
    {
        name: "Catppuccin Mocha",
        colors: {
            primary: "#89DCEB",
            planMode: "#CBA6F7",
            selection: "#89B4FA",
            thinking: "#CBA6F7",
            success: "#A6E3A1",
            error: "#F38BA8",
            info: "#89DCEB",
            background: "#1E1E2E",
            surface: "#181825",
            dialogSurface: "#11111B",
            thinkingBoarder: "#313244",
            dimSeparator: "#45475A",
        },
    },
    {
        name: "Gruvbox Dark",
        colors: {
            primary: "#8EC07C",
            planMode: "#D3869B",
            selection: "#458588",
            thinking: "#D3869B",
            success: "#B8BB26",
            error: "#FB4934",
            info: "#83A598",
            background: "#1D2021",
            surface: "#282828",
            dialogSurface: "#16181A",
            thinkingBoarder: "#3C3836",
            dimSeparator: "#504945",
        },
    },
    {
        name: "Dracula Pro",
        colors: {
            primary: "#8BE9FD",
            planMode: "#FF79C6",
            selection: "#6272A4",
            thinking: "#FF79C6",
            success: "#50FA7B",
            error: "#FF5555",
            info: "#8BE9FD",
            background: "#1C1E26",
            surface: "#242636",
            dialogSurface: "#16181E",
            thinkingBoarder: "#30324A",
            dimSeparator: "#44475A",
        },
    },
    {
        name: "Everforest",
        colors: {
            primary: "#83C092",
            planMode: "#D699B6",
            selection: "#7FBBB3",
            thinking: "#D699B6",
            success: "#A7C080",
            error: "#E67E80",
            info: "#7FBBB3",
            background: "#1E2326",
            surface: "#272E33",
            dialogSurface: "#191C1F",
            thinkingBoarder: "#323D43",
            dimSeparator: "#4A555B",
        },
    },
    {
        name: "Nord",
        colors: {
            primary: "#88C0D0",
            planMode: "#B48EAD",
            selection: "#5E81AC",
            thinking: "#B48EAD",
            success: "#A3BE8C",
            error: "#BF616A",
            info: "#88C0D0",
            background: "#1C2028",
            surface: "#242933",
            dialogSurface: "#161A21",
            thinkingBoarder: "#2E3440",
            dimSeparator: "#434C5E",
        },
    },
    {
        name: "Synthwave '84",
        colors: {
            primary: "#36F9F6",
            planMode: "#FF7EDB",
            selection: "#7B5EA7",
            thinking: "#FF7EDB",
            success: "#72F1B8",
            error: "#FE4450",
            info: "#36F9F6",
            background: "#0D0921",
            surface: "#1A1033",
            dialogSurface: "#080614",
            thinkingBoarder: "#2A1F52",
            dimSeparator: "#4A3780",
        },
    },
    {
        name: "Solarized Dark",
        colors: {
            primary: "#2AA198",
            planMode: "#D33682",
            selection: "#268BD2",
            thinking: "#D33682",
            success: "#859900",
            error: "#DC322F",
            info: "#268BD2",
            background: "#00212B",
            surface: "#002B36",
            dialogSurface: "#001A22",
            thinkingBoarder: "#073642",
            dimSeparator: "#15606B",
        },
    },
    {
        name: "One Dark Pro",
        colors: {
            primary: "#56B6C2",
            planMode: "#C678DD",
            selection: "#3E4451",
            thinking: "#C678DD",
            success: "#98C379",
            error: "#E06C75",
            info: "#61AFEF",
            background: "#1B1F27",
            surface: "#21252B",
            dialogSurface: "#16191F",
            thinkingBoarder: "#2C313A",
            dimSeparator: "#3E4451",
        },
    },
    {
        name: "Moonlight",
        colors: {
            primary: "#86E1FC",
            planMode: "#BB9AF7",
            selection: "#2D4F67",
            thinking: "#BB9AF7",
            success: "#C3E88D",
            error: "#FF757F",
            info: "#86E1FC",
            background: "#212337",
            surface: "#191A2A",
            dialogSurface: "#131421",
            thinkingBoarder: "#2F3354",
            dimSeparator: "#444A73",
        },
    },
    {
        name: "Kanagawa",
        colors: {
            primary: "#7FB4CA",
            planMode: "#957FB8",
            selection: "#2D4F67",
            thinking: "#957FB8",
            success: "#76946A",
            error: "#C34043",
            info: "#7FB4CA",
            background: "#1F1F28",
            surface: "#16161D",
            dialogSurface: "#0D0C0C",
            thinkingBoarder: "#2A2A37",
            dimSeparator: "#54546D",
        },
    },
    {
        name: "Cobalt2",
        colors: {
            primary: "#9EFFFF",
            planMode: "#FB94FF",
            selection: "#0050A4",
            thinking: "#FB94FF",
            success: "#3AD900",
            error: "#FF2600",
            info: "#9EFFFF",
            background: "#112B3E",
            surface: "#193549",
            dialogSurface: "#0C1E2E",
            thinkingBoarder: "#1F4363",
            dimSeparator: "#335A7A",
        },
    },
    {
        name: "Material Palenight",
        colors: {
            primary: "#89DDFF",
            planMode: "#C792EA",
            selection: "#717CB4",
            thinking: "#C792EA",
            success: "#C3E88D",
            error: "#F07178",
            info: "#82AAFF",
            background: "#1B1E2B",
            surface: "#202331",
            dialogSurface: "#131520",
            thinkingBoarder: "#2B2E3B",
            dimSeparator: "#3C3F5C",
        },
    },
    {
        name: "Horizon",
        colors: {
            primary: "#25B0BC",
            planMode: "#B877DB",
            selection: "#1F4662",
            thinking: "#B877DB",
            success: "#09F7A0",
            error: "#E95679",
            info: "#25B0BC",
            background: "#1C1E26",
            surface: "#232530",
            dialogSurface: "#15161E",
            thinkingBoarder: "#2E303E",
            dimSeparator: "#41434F",
        },
    },
    {
        name: "Ayu Dark",
        colors: {
            primary: "#39BAE6",
            planMode: "#D2A6FF",
            selection: "#0D2A4D",
            thinking: "#D2A6FF",
            success: "#7FD962",
            error: "#FF3333",
            info: "#39BAE6",
            background: "#0B0E14",
            surface: "#13161C",
            dialogSurface: "#080A0F",
            thinkingBoarder: "#1D2433",
            dimSeparator: "#2D3446",
        },
    },
];

export const DEFAULT_THEME = THEMES.find((t) => t.name === "Nightfox")!;